class ConfirmAllClassRenames < ActiveRecord::Migration
  include MigrationHelper

  NAME_MAP = Hash[*%w(
    MiqEvent                                              MiqEventDefinition
    MiqEventSet                                           MiqEventDefinitionSet

    MiqEventCatcher                                       NOVAHawk::Providers::BaseManager::EventCatcher
    MiqEmsMetricsCollectorWorker                          NOVAHawk::Providers::BaseManager::MetricsCollectorWorker
    MiqEmsRefreshWorker                                   NOVAHawk::Providers::BaseManager::RefreshWorker
    EmsRefresh::Refreshers::BaseRefresher                 NOVAHawk::Providers::BaseManager::Refresher
    EmsCloud                                              NOVAHawk::Providers::CloudManager
    AuthKeyPairCloud                                      NOVAHawk::Providers::CloudManager::AuthKeyPair
    MiqProvisionCloud                                     NOVAHawk::Providers::CloudManager::Provision
    MiqProvisionCloudWorkflow                             NOVAHawk::Providers::CloudManager::ProvisionWorkflow
    EmsRefresh::Parsers::Cloud                            NOVAHawk::Providers::CloudManager::RefreshParser
    TemplateCloud                                         NOVAHawk::Providers::CloudManager::Template
    VmCloud                                               NOVAHawk::Providers::CloudManager::Vm
    ConfigurationManager                                  NOVAHawk::Providers::ConfigurationManager
    EmsContainer                                          NOVAHawk::Providers::ContainerManager
    EmsInfra                                              NOVAHawk::Providers::InfraManager
    MiqProvisionInfraWorkflow                             NOVAHawk::Providers::InfraManager::ProvisionWorkflow
    TemplateInfra                                         NOVAHawk::Providers::InfraManager::Template
    VmInfra                                               NOVAHawk::Providers::InfraManager::Vm
    ProvisioningManager                                   NOVAHawk::Providers::ProvisioningManager

    EmsAmazon                                             NOVAHawk::Providers::Amazon::CloudManager
    AuthKeyPairAmazon                                     NOVAHawk::Providers::Amazon::CloudManager::AuthKeyPair
    AvailabilityZoneAmazon                                NOVAHawk::Providers::Amazon::CloudManager::AvailabilityZone
    CloudVolumeAmazon                                     NOVAHawk::Providers::Amazon::CloudManager::CloudVolume
    CloudVolumeSnapshotAmazon                             NOVAHawk::Providers::Amazon::CloudManager::CloudVolumeSnapshot
    MiqEventCatcherAmazon                                 NOVAHawk::Providers::Amazon::CloudManager::EventCatcher
    FlavorAmazon                                          NOVAHawk::Providers::Amazon::CloudManager::Flavor
    FloatingIpAmazon                                      NOVAHawk::Providers::Amazon::CloudManager::FloatingIp
    MiqEmsMetricsCollectorWorkerAmazon                    NOVAHawk::Providers::Amazon::CloudManager::MetricsCollectorWorker
    ServiceOrchestration::OptionConverterAmazon           NOVAHawk::Providers::Amazon::CloudManager::OrchestrationServiceOptionConverter
    OrchestrationStackAmazon                              NOVAHawk::Providers::Amazon::CloudManager::OrchestrationStack
    MiqProvisionAmazon                                    NOVAHawk::Providers::Amazon::CloudManager::Provision
    MiqProvisionAmazonWorkflow                            NOVAHawk::Providers::Amazon::CloudManager::ProvisionWorkflow
    EmsRefresh::Parsers::Ec2                              NOVAHawk::Providers::Amazon::CloudManager::RefreshParser
    MiqEmsRefreshWorkerAmazon                             NOVAHawk::Providers::Amazon::CloudManager::RefreshWorker
    EmsRefresh::Refreshers::Ec2Refresher                  NOVAHawk::Providers::Amazon::CloudManager::Refresher
    SecurityGroupAmazon                                   NOVAHawk::Providers::Amazon::CloudManager::SecurityGroup
    TemplateAmazon                                        NOVAHawk::Providers::Amazon::CloudManager::Template
    VmAmazon                                              NOVAHawk::Providers::Amazon::CloudManager::Vm
    ConfigurationManagerForeman                           NOVAHawk::Providers::Foreman::ConfigurationManager
    ConfigurationProfileForeman                           NOVAHawk::Providers::Foreman::ConfigurationManager::ConfigurationProfile
    ConfiguredSystemForeman                               NOVAHawk::Providers::Foreman::ConfigurationManager::ConfiguredSystem
    MiqProvisionTaskConfiguredSystemForeman               NOVAHawk::Providers::Foreman::ConfigurationManager::ProvisionTask
    MiqProvisionConfiguredSystemForemanWorkflow           NOVAHawk::Providers::Foreman::ConfigurationManager::ProvisionWorkflow
    MiqEmsRefreshWorkerForemanConfiguration               NOVAHawk::Providers::Foreman::ConfigurationManager::RefreshWorker
    EmsRefresh::Refreshers::ForemanConfigurationRefresher NOVAHawk::Providers::Foreman::ConfigurationManager::Refresher
    ProviderForeman                                       NOVAHawk::Providers::Foreman::Provider
    ProvisioningManagerForeman                            NOVAHawk::Providers::Foreman::ProvisioningManager
    EmsRefresh::Parsers::Foreman                          NOVAHawk::Providers::Foreman::ProvisioningManager::RefreshParser
    MiqEmsRefreshWorkerForemanProvisioning                NOVAHawk::Providers::Foreman::ProvisioningManager::RefreshWorker
    EmsRefresh::Refreshers::ForemanProvisioningRefresher  NOVAHawk::Providers::Foreman::ProvisioningManager::Refresher
    EmsKubernetes                                         NOVAHawk::Providers::Kubernetes::ContainerManager
    MiqEventCatcherKubernetes                             NOVAHawk::Providers::Kubernetes::ContainerManager::EventCatcher
    EmsRefresh::Parsers::Kubernetes                       NOVAHawk::Providers::Kubernetes::ContainerManager::RefreshParser
    MiqEmsRefreshWorkerKubernetes                         NOVAHawk::Providers::Kubernetes::ContainerManager::RefreshWorker
    EmsRefresh::Refreshers::KubernetesRefresher           NOVAHawk::Providers::Kubernetes::ContainerManager::Refresher
    EmsMicrosoft                                          NOVAHawk::Providers::Microsoft::InfraManager
    HostMicrosoft                                         NOVAHawk::Providers::Microsoft::InfraManager::Host
    EmsMicrosoft::Powershell                              NOVAHawk::Providers::Microsoft::InfraManager::Powershell
    EmsRefresh::Parsers::Scvmm                            NOVAHawk::Providers::Microsoft::InfraManager::RefreshParser
    MiqEmsRefreshWorkerMicrosoft                          NOVAHawk::Providers::Microsoft::InfraManager::RefreshWorker
    EmsRefresh::Refreshers::ScvmmRefresher                NOVAHawk::Providers::Microsoft::InfraManager::Refresher
    TemplateMicrosoft                                     NOVAHawk::Providers::Microsoft::InfraManager::Template
    VmMicrosoft                                           NOVAHawk::Providers::Microsoft::InfraManager::Vm
    EmsOpenstack                                          NOVAHawk::Providers::Openstack::CloudManager
    AvailabilityZoneOpenstack                             NOVAHawk::Providers::Openstack::CloudManager::AvailabilityZone
    AvailabilityZoneOpenstackNull                         NOVAHawk::Providers::Openstack::CloudManager::AvailabilityZoneNull
    CloudResourceQuotaOpenstack                           NOVAHawk::Providers::Openstack::CloudManager::CloudResourceQuota
    CloudTenantOpenstack                                  NOVAHawk::Providers::Openstack::CloudManager::CloudTenant
    CloudVolumeOpenstack                                  NOVAHawk::Providers::Openstack::CloudManager::CloudVolume
    CloudVolumeSnapshotOpenstack                          NOVAHawk::Providers::Openstack::CloudManager::CloudVolumeSnapshot
    MiqEventCatcherOpenstack                              NOVAHawk::Providers::Openstack::CloudManager::EventCatcher
    FlavorOpenstack                                       NOVAHawk::Providers::Openstack::CloudManager::Flavor
    FloatingIpOpenstack                                   NOVAHawk::Providers::Openstack::CloudManager::FloatingIp
    MiqEmsMetricsCollectorWorkerOpenstack                 NOVAHawk::Providers::Openstack::CloudManager::MetricsCollectorWorker
    ServiceOrchestration::OptionConverterOpenstack        NOVAHawk::Providers::Openstack::CloudManager::OrchestrationServiceOptionConverter
    OrchestrationStackOpenstack                           NOVAHawk::Providers::Openstack::CloudManager::OrchestrationStack
    MiqProvisionOpenstack                                 NOVAHawk::Providers::Openstack::CloudManager::Provision
    MiqProvisionOpenstackWorkflow                         NOVAHawk::Providers::Openstack::CloudManager::ProvisionWorkflow
    EmsRefresh::Parsers::Openstack                        NOVAHawk::Providers::Openstack::CloudManager::RefreshParser
    MiqEmsRefreshWorkerOpenstack                          NOVAHawk::Providers::Openstack::CloudManager::RefreshWorker
    EmsRefresh::Refreshers::OpenstackRefresher            NOVAHawk::Providers::Openstack::CloudManager::Refresher
    SecurityGroupOpenstack                                NOVAHawk::Providers::Openstack::CloudManager::SecurityGroup
    TemplateOpenstack                                     NOVAHawk::Providers::Openstack::CloudManager::Template
    VmOpenstack                                           NOVAHawk::Providers::Openstack::CloudManager::Vm
    VmOpenstack::RemoteConsole                            NOVAHawk::Providers::Openstack::CloudManager::Vm::RemoteConsole
    EmsOpenstackInfra                                     NOVAHawk::Providers::Openstack::InfraManager
    AuthKeyPairOpenstack                                  NOVAHawk::Providers::Openstack::InfraManager::AuthKeyPair
    MiqEventCatcherOpenstackInfra                         NOVAHawk::Providers::Openstack::InfraManager::EventCatcher
    HostOpenstackInfra                                    NOVAHawk::Providers::Openstack::InfraManager::Host
    MiqEmsMetricsCollectorWorkerOpenstackInfra            NOVAHawk::Providers::Openstack::InfraManager::MetricsCollectorWorker
    OrchestrationStackOpenstackInfra                      NOVAHawk::Providers::Openstack::InfraManager::OrchestrationStack
    EmsRefresh::Parsers::OpenstackInfra                   NOVAHawk::Providers::Openstack::InfraManager::RefreshParser
    MiqEmsRefreshWorkerOpenstackInfra                     NOVAHawk::Providers::Openstack::InfraManager::RefreshWorker
    EmsRefresh::Refreshers::OpenstackInfraRefresher       NOVAHawk::Providers::Openstack::InfraManager::Refresher
    ProviderOpenstack                                     NOVAHawk::Providers::Openstack::Provider
    EmsRedhat                                             NOVAHawk::Providers::Redhat::InfraManager
    MiqEventCatcherRedhat                                 NOVAHawk::Providers::Redhat::InfraManager::EventCatcher
    HostRedhat                                            NOVAHawk::Providers::Redhat::InfraManager::Host
    MiqEmsMetricsCollectorWorkerRedhat                    NOVAHawk::Providers::Redhat::InfraManager::MetricsCollectorWorker
    MiqProvisionRedhat                                    NOVAHawk::Providers::Redhat::InfraManager::Provision
    MiqProvisionRedhatViaIso                              NOVAHawk::Providers::Redhat::InfraManager::ProvisionViaIso
    MiqProvisionRedhatViaPxe                              NOVAHawk::Providers::Redhat::InfraManager::ProvisionViaPxe
    MiqProvisionRedhatWorkflow                            NOVAHawk::Providers::Redhat::InfraManager::ProvisionWorkflow
    MiqEmsRefreshWorkerRedhat                             NOVAHawk::Providers::Redhat::InfraManager::RefreshWorker
    EmsRefresh::Refreshers::RhevmRefresher                NOVAHawk::Providers::Redhat::InfraManager::Refresher
    TemplateRedhat                                        NOVAHawk::Providers::Redhat::InfraManager::Template
    VmRedhat                                              NOVAHawk::Providers::Redhat::InfraManager::Vm
    VmRedhat::RemoteConsole                               NOVAHawk::Providers::Redhat::InfraManager::Vm::RemoteConsole
    EmsVmware                                             NOVAHawk::Providers::Vmware::InfraManager
    MiqEventCatcherVmware                                 NOVAHawk::Providers::Vmware::InfraManager::EventCatcher
    HostVmware                                            NOVAHawk::Providers::Vmware::InfraManager::Host
    HostVmwareEsx                                         NOVAHawk::Providers::Vmware::InfraManager::HostEsx
    MiqEmsMetricsCollectorWorkerVmware                    NOVAHawk::Providers::Vmware::InfraManager::MetricsCollectorWorker
    MiqProvisionVmware                                    NOVAHawk::Providers::Vmware::InfraManager::Provision
    MiqProvisionVmwareViaPxe                              NOVAHawk::Providers::Vmware::InfraManager::ProvisionViaPxe
    MiqProvisionVmwareWorkflow                            NOVAHawk::Providers::Vmware::InfraManager::ProvisionWorkflow
    EmsRefresh::Parsers::Vc                               NOVAHawk::Providers::Vmware::InfraManager::RefreshParser
    EmsRefresh::Parsers::Vc::Filter                       NOVAHawk::Providers::Vmware::InfraManager::RefreshParser::Filter
    MiqEmsRefreshWorkerVmware                             NOVAHawk::Providers::Vmware::InfraManager::RefreshWorker
    EmsRefresh::Refreshers::VcRefresher                   NOVAHawk::Providers::Vmware::InfraManager::Refresher
    TemplateVmware                                        NOVAHawk::Providers::Vmware::InfraManager::Template
    VmVmware                                              NOVAHawk::Providers::Vmware::InfraManager::Vm
  )]

  def change
    say_with_time "Rename class references" do
      rename_class_references(NAME_MAP)
    end
  end
end
