# rubocop:disable Metrics/LineLength
module MiqAeMethodService
  class MiqAeServiceNOVAHawk_Providers_Google_CloudManager_VirtualTemplate < MiqAeServiceNOVAHawk_Providers_CloudManager_Template
  end
end
